import {
    Box,
    Button,
    Flex,
    FormControl,
    FormLabel,
    Heading,
    Input,
    Text,
    Textarea,
} from "@chakra-ui/react";
import { yupResolver } from "@hookform/resolvers/yup";
import Head from "next/head";
import { FunctionComponent } from "react";
import { useForm } from "react-hook-form";
import * as yup from "yup";

interface IUserFormData {
  fistName: String;
  lastName: String;
  email: String;
  address: String;
  phone: String;
  description: String;
  onSubmit: () => void;
  handleSubmit: () => void;
}

const schema = yup.object({
  fistName: yup.string().required(),
  lastName: yup.string().required(),
  email: yup.string().required(),
  address: yup.string().required(),
  phone: yup.string().required(),
  description: yup.string().required(),
});

interface IHomePops {
  fistName: String;
  lastName: String;
  email: String;
  address: String;
  phone: String;
  description: String;
  onSubmit: () => void;
  handleSubmit: () => void;
}

const Cadastro: FunctionComponent<IHomePops> = () => {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<IUserFormData>({
    resolver: yupResolver(schema),
  });
  const onSubmit = (data: Object) => {
    console.log(data);
  };

  return (
    <>
      <Head>
        <title>Formulário com NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex
          minHeight="100vh"
          width="full"
          align="center"
          justifyContent="center"
          backgroundColor="gray.900"
        >
          <Box
            px={12}
            py={12}
            width="full"
            maxWidth="450px"
            textAlign="center"
            boxShadow="lg"
            background="gray.700"
            borderRadius="6px"
          >
            <Heading>
              <Text color="gray.200" fontSize="2xl">
                Registrar-se
              </Text>
            </Heading>
            <Box>
              <form
                action=""
                autoComplete="off"
                onSubmit={handleSubmit(onSubmit)}
              >
                <Flex justify="space-between">
                  <FormControl isRequired marginTop="15px" width="49%">
                    <FormLabel color="gray.200">Primeiro nome</FormLabel>
                    <Input
                      type="text"
                      border="none"
                      outline="none"
                      bgColor="gray.900"
                      focusBorderColor="gray.600"
                      color="gray.200"
                      placeholder="Nome"
                      {...register("fistName")}
                    />
                    <p style={{ color: "red" }}>{errors.fistName?.message}</p>
                  </FormControl>
                  <FormControl isRequired marginTop="15px" width="49%">
                    <FormLabel color="gray.200">Sobrenome</FormLabel>
                    <Input
                      type="text"
                      border="none"
                      outline="none"
                      bgColor="gray.900"
                      focusBorderColor="gray.600"
                      color="gray.200"
                      placeholder="Sobrenome"
                      {...register("lastName")}
                    />
                    <p style={{ color: "red" }}>{errors.lastName?.message}</p>
                  </FormControl>
                </Flex>
                <FormControl isRequired marginTop="15px">
                  <FormLabel color="gray.200">Email</FormLabel>
                  <Input
                    type="email"
                    border="none"
                    outline="none"
                    bgColor="gray.900"
                    focusBorderColor="gray.600"
                    color="gray.200"
                    placeholder="Email"
                    {...register("email")}
                  />
                  <p style={{ color: "red" }}>{errors.email?.message}</p>
                </FormControl>
                <Flex justify="space-between">
                  <FormControl isRequired marginTop="15px" width="49%">
                    <FormLabel color="gray.200">Endereço</FormLabel>
                    <Input
                      type="text"
                      border="none"
                      outline="none"
                      bgColor="gray.900"
                      focusBorderColor="gray.600"
                      color="gray.200"
                      placeholder="Endereço"
                      {...register("address")}
                    />
                    <p style={{ color: "red" }}>{errors.address?.message}</p>
                  </FormControl>
                  <FormControl isRequired marginTop="15px" width="49%">
                    <FormLabel color="gray.200">Telefone</FormLabel>
                    <Input
                      type="text"
                      border="none"
                      outline="none"
                      bgColor="gray.900"
                      focusBorderColor="gray.600"
                      color="gray.200"
                      placeholder="Telefone"
                      {...register("phone")}
                    />
                    <p style={{ color: "red" }}>{errors.phone?.message}</p>
                  </FormControl>
                </Flex>
                <FormControl isRequired marginTop="15px">
                  <FormLabel color="gray.200">Message</FormLabel>
                  <Textarea
                    border="none"
                    outline="none"
                    bgColor="gray.900"
                    focusBorderColor="gray.600"
                    color="gray.200"
                    placeholder="Message"
                    resize="none"
                    {...register("description")}
                  />
                </FormControl>
                <Button
                  type="submit"
                  width="full"
                  bgColor="green.400"
                  mt={4}
                  color="gray.200"
                  _hover={{ color: "black" }}
                >
                  Registrar
                </Button>
              </form>
            </Box>
          </Box>
        </Flex>
      </main>
    </>
  );
};

export default Cadastro;
