import Head from 'next/head'
import { Button, Textarea, FormControl, FormLabel, Input, Heading, Text, Box, Flex } from '@chakra-ui/react'
import { FormEvent, FunctionComponent, useState } from 'react'

interface IHomePops {
  fistName: String;
  lastName: String;
  email: String;
  address: String;
  phone: String;
  description: String;
}

const Home: FunctionComponent<IHomePops> = () => {
  const [fistName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [email, setEmail] = useState('');
  const [address, setAddress] = useState('');
  const [phone, setPhone] = useState('');
  const [description, setDescription] = useState('');

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();

    const data = {
      fistName,
      lastName,
      email,
      address,
      phone,
      description,
    }
    console.log(data);
  }

  return (
    <>
      <Head>
        <title>Formulário com NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex minHeight='100vh' width='full' align='center' justifyContent='center' backgroundColor='gray.900'>
          <Box px={12} py={12} width='full' maxWidth='450px' textAlign='center' boxShadow='lg' background='gray.700' borderRadius='6px'>
            <Heading>
              <Text color='gray.200' fontSize='2xl'>Registrar-se</Text>
            </Heading>
            <Box>
              <form action='' autoComplete='off' onSubmit={handleSubmit}>
                <Flex justify='space-between'>
                  <FormControl isRequired marginTop='15px' width='49%'>
                    <FormLabel color='gray.200'>Primeiro nome</FormLabel>
                    <Input type='text' name='Fistname' border='none' outline='none' bgColor='gray.900' focusBorderColor='gray.600' color='gray.200' placeholder='Nome' onChange={(e) => setFirstName(e.target.value)} />
                  </FormControl>
                  <FormControl isRequired marginTop='15px' width='49%'>
                    <FormLabel color='gray.200'>Sobrenome</FormLabel>
                    <Input type='email' name='Lastname' border='none' outline='none' bgColor='gray.900' focusBorderColor='gray.600' color='gray.200' placeholder='Sobrenome' onChange={(e) => setLastName(e.target.value)} />
                  </FormControl>
                </Flex>
                <FormControl isRequired marginTop='15px'>
                  <FormLabel color='gray.200'>Email</FormLabel>
                  <Input type='email' name='email' border='none' outline='none' bgColor='gray.900' focusBorderColor='gray.600' color='gray.200' placeholder='Email' onChange={(e) => setEmail(e.target.value)} />
                </FormControl>
                <Flex justify='space-between'>
                  <FormControl isRequired marginTop='15px' width='49%'>
                    <FormLabel color='gray.200'>Endereço</FormLabel>
                    <Input type='email' name='address' border='none' outline='none' bgColor='gray.900' focusBorderColor='gray.600' color='gray.200' placeholder='Endereço' onChange={(e) => setAddress(e.target.value)} />
                  </FormControl>
                  <FormControl isRequired marginTop='15px' width='49%'>
                    <FormLabel color='gray.200'>Telefone</FormLabel>
                    <Input type='email' name='phone' border='none' outline='none' bgColor='gray.900' focusBorderColor='gray.600' color='gray.200' placeholder='Telefone' onChange={(e) => setPhone(e.target.value)} />
                  </FormControl>
                </Flex>
                <FormControl isRequired marginTop='15px'>
                  <FormLabel color='gray.200'>Message</FormLabel>
                  <Textarea border='none' name='description' outline='none' bgColor='gray.900' focusBorderColor='gray.600' color='gray.200' placeholder='Message' resize='none' onChange={(e) => setDescription(e.target.value)} />
                </FormControl>
                <Button type='submit' width='full' bgColor='green.400' mt={4} color='gray.200' _hover={{ color: 'black' }}>Registrar</Button>
              </form>
            </Box>
          </Box>
        </Flex>
      </main>
    </>
  )
}

export default Home;